core_classes = [
    "Cleric",
    "Thief",
    "Warrior",
    "Wizard",
]

weird_classes = [
    "Barbarian",
    "Rogue",
    "Wizard",
    "Cleric",
    "Fighter",
    "Bard",
    "Druid",
    "Monk",
    "Sorcerer",
    "Paladin",
    "Warlock",
    "Ranger",
    "Necromancer",
    "Assassin",
    "Summoner",
    "Warrior",
    "Berserker",
    "Shadow",
    "Elementalist",
    "Alchemist",
    "Mystic",
    "Thief",
    "Archer",
    "Sellsword",
    "Swashbuckler",
    "Crusader",
    "Spellblade",
    "Arcanist",
    "Priest",
    "Inquisitor",
    "Shaman",
    "Bountyhunter",
    "Witch",
    "Gladiator",
    "Conjurer",
    "Brawler",
    "Acolyte",
    "Scout",
    "Beastmaster",
    "Hunter",
    "Trickster",
    "Blademaster",
    "Warrior-Poet",
    "Zealot",
    "Martialist",
    "Burglar",
    "Savant",
    "Geomancer",
    "Runekeeper",
    "Psion",
    "Soothsayer",
    "Juggernaut",
    "Nightblade",
    "Arbiter",
    "Spellslinger",
    "Swordmage",
    "Deathdealer",
    "Warlord",
    "Diviner",
    "Shadowdancer",
    "Runemage",
    "Swordmaster",
    "Dragonslayer",
    "Hellion",
    "Artificer",
    "Spellweaver",
    "Vanguard",
    "Reaper",
    "Riftwalker",
    "Bladesinger",
    "Gunslinger",
    "Apocalypse",
    "Elemental",
    "Bloodmage",
    "Bane",
    "Corsair",
    "Oracle",
    "Tactician",
    "Skald",
    "Venomancer",
    "Celestial",
    "Chronomancer",
    "Executioner",
    "Deathknight",
    "Crusader",
    "Voidwalker",
    "Stormcaller",
    "Shadowblade",
    "Illusionist",
    "Spellbinder",
    "Demonhunter",
    "Templar",
    "Pyromancer",
    "Geomancer",
    "Frostborn",
    "Mindflayer",
    "Warpriest",
    "Bladeweaver",
    "Elf",
    "Dwarf",
    "Human",
    "Halfling",
    "Orc",
    "Goblin",
    "Troll",
    "Gnome",
    "Dragonborn",
    "Kobold",
    "Centaur",
    "Minotaur",
    "Satyr",
    "Gnoll",
    "Lizardfolk",
    "Aasimar",
    "Tiefling",
    "Firbolg",
    "Tabaxi",
    "Kenku",
    "Aarakocra",
    "Genasi",
    "Triton",
    "Goliath",
    "Half-Elf",
    "Half-Orc",
    "Halfing",
    "Gith",
    "Yuan-ti",
    "Hobgoblin",
    "Bugbear",
    "Githzerai",
    "Duergar",
    "Tortle",
    "Changeling",
    "Shifter",
    "Warforged",
    "Goliath",
    "Kalashtar",
    "Loxodon",
    "Simic Hybrid",
    "Vedalken",
    "Viashino",
    "Verdan",
    "Locathah",
    "Siren",
    "Leprechaun",
    "Myconid",
    "Thri-kreen",
    "Shardmind",
    "Warforged",
    "Satyr",
    "Lizardfolk",
    "Aasimar",
    "Tabaxi",
    "Kenku",
    "Aarakocra",
    "Genasi",
    "Triton",
    "Goliath",
    "Half-Elf",
    "Half-Orc",
    "Halfing",
    "Gith",
    "Yuan-ti",
    "Hobgoblin",
    "Bugbear",
    "Githzerai",
    "Duergar",
    "Tortle",
    "Changeling",
    "Shifter",
    "Warforged",
    "Goliath",
    "Kalashtar",
    "Loxodon",
    "Simic Hybrid",
    "Vedalken",
    "Viashino",
    "Verdan",
    "Locathah",
    "Siren",
    "Leprechaun",
    "Myconid",
    "Thri-kreen",
    "Shardmind",
    "Warforged",
    "Satyr",
    "Lizardfolk",
    "Aasimar",
    "Tabaxi",
    "Kenku",
    "Aarakocra",
    "Genasi",
    "Triton",
    "Goliath",
    "Half-Elf",
    "Half-Orc",
    "Halfing",
    "Gith",
    "Yuan-ti",
    "Hobgoblin",
    "Bugbear",
    "Githzerai",
    "Duergar",
    "Tortle",
    "Changeling",
    "Shifter",
    "Warforged",
    "Divine Paladin",
    "Arcane Mage",
    "Stealthy Rogue",
    "Holy Cleric",
    "Mighty Barbarian",
    "Shadowy Assassin",
    "Nature Druid",
    "Mystic Sorcerer",
    "Battle Bard",
    "Wise Wizard",
    "Valor Knight",
    "Cunning Trickster",
    "Savage Berserker",
    "Elemental Conjurer",
    "Swift Ranger",
    "Deathly Necromancer",
    "Celestial Priest",
    "Feral Beastmaster",
    "Vengeful Avenger",
    "Martial Monk",
    "Enigmatic Warlock",
    "Wild Shaman",
    "Arcane Trickster",
    "Divine Knight",
    "Spiritual Monk",
    "Spellcasting Warlock",
    "Ancient Druid",
    "Fiery Pyromancer",
    "Shadow Rogue",
    "Nature's Guardian",
    "Arcane Scholar",
    "Thundering Berserker",
    "Frosty Cryomancer",
    "Holy Inquisitor",
    "Deadly Duelist",
    "Spectral Illusionist",
    "Swift Scout",
    "Radiant Cleric",
    "Chaos Sorcerer",
    "Frosty Spellblade",
    "Arcane Archer",
    "Necrotic Deathknight",
    "Vengeful Revenant",
    "Holy Crusader",
    "Cursed Warlock",
    "Nature's Warden",
    "Doomsayer Necromancer",
    "Stealthy Assassin",
    "Arcane Enchanter",
    "Celestial Cleric",
    "Vengeful Spirit",
    "Savage Barbarian",
    "Mystic Oracle",
    "Fiery Pyromancer",
    "Shadowy Infiltrator",
    "Arcane Arcanist",
    "Frosty Frostcaller",
    "Holy Paladin",
    "Thundering Stormcaller",
    "Ethereal Sorcerer",
    "Divine Guardian",
    "Noble Knight",
    "Arcane Alchemist",
    "Swift Bladesinger",
    "Celestial Avenger",
    "Vengeful Harbinger",
    "Frosty Frostguard",
    "Shadowy Shade",
    "Savage Savage",
    "Arcane Artificer",
    "Radiant Redeemer",
    "Eldritch Warlock",
    "Celestial Seraph",
    "Holy Exorcist",
    "Necrotic Dreadknight",
    "Arcane Arcanum",
    "Frosty Frostborn",
    "Shadowy Stalker",
    "Divine Diviner",
    "Savage Marauder",
    "Ethereal Evoker",
    "Celestial Luminary",
    "Arcane Archmage",
    "Necrotic Gravekeeper",
    "Mystic Magician",
    "Fiery Flamecaller",
    "Divine Crusader",
    "Shadowy Nightblade",
    "Urban Shaman",
    "Streetwise Bard",
    "Concrete Druid",
    "Underground Sorcerer",
    "Graffiti Mage",
    "Cybernetic Hacker",
    "Bricklayer Berserker",
    "Traffic Jam Cleric",
    "Sewer Rogue",
    "Subway Monk",
    "Alleyway Assassin",
    "Metro Paladin",
    "Skyscraper Summoner",
    "Roof-Runner Ranger",
    "Industrial Barbarian",
    "Freeway Warlock",
    "Recycler Rogue",
    "Dumpster Diver Druid",
    "Pothole Paladin",
    "Gutter Bard",
    "Highwayman Hunter",
    "Sidewalk Sorcerer",
    "Parkour Monk",
    "Rooftop Sniper",
    "Underground Bard",
    "Trashcan Druid",
    "Steelworker Sorcerer",
    "Junkyard Mechanic",
    "Neon Necromancer",
    "Wasteland Warrior",
    "Pavement Priest",
    "Cityscape Sorcerer",
    "Bike Messenger Monk",
    "Riot Bard",
    "Construction Cleric",
    "Concrete Conjurer",
    "Dumpster Diver Druid",
    "Metro Magician",
    "Streetlight Summoner",
    "Skateboarder Sorcerer",
    "Graffiti Artist Bard",
    "Traffic Warden Warlock",
    "Steelworker Shaman",
    "Subway Swashbuckler",
    "Urban Tracker Ranger",
    "Busker Bard",
    "Rooftop Ranger",
    "Back-Alley Brawler",
    "Underground Mechanic",
    "Alleycat Assassin",
    "Concrete Cowboy",
    "Freeway Fighter",
    "Skyline Sorcerer",
    "Skyscraper Sniper",
    "Rooftop Rebel",
    "Subway Shaman",
    "Street Smart Sorcerer",
    "Cityscape Summoner",
    "Sewer Scavenger",
    "Sidewalk Shaman",
    "Metro Mercenary",
    "Graffiti Guru",
    "Urban Outlaw",
    "Streetwise Sorcerer",
    "Rooftop Ranger",
    "Concrete Conjurer",
    "Alleycat Assassin",
    "Cityscape Cleric",
    "Subway Sorcerer",
    "Graffiti Bard",
    "Streetlight Summoner",
    "Dumpster Diver Druid",
    "Cybernetic Cleric",
    "Pavement Paladin",
    "Steelworker Shaman",
    "Neon Necromancer",
    "Freeway Fighter",
    "Rooftop Rebel",
    "Urban Tracker Ranger",
    "Gutter Bard",
    "Bricklayer Berserker",
    "Underground Mechanic",
    "Pothole Priest",
    "Skateboarder Sorcerer",
    "Street Smart Sorcerer",
    "Concrete Cowboy",
    "Sidewalk Sorcerer",
    "Traffic Jam Cleric",
    "Industrial Barbarian",
    "Subway Swashbuckler",
    "Cybernetic Hacker",
    "Cityscape Sorcerer",
    "Urban Shaman",
    "Concrete Druid",
    "Alleyway Assassin",
    "Riot Bard",
    "Steelworker Sorcerer",
    "Concrete Guardian",
    "Street Samurai",
    "Cityscape Slicer",
    "Neon Navigator",
    "Urban Enforcer",
    "Gutter Guardian",
    "Skyscraper Sentinel",
    "Sewer Squire",
    "Alleyway Adept",
    "Highway Hunter",
    "Freeway Fury",
    "Metro Mage",
    "Subway Sentinel",
    "Graffiti Goliath",
    "Rooftop Ranger",
    "Pavement Protector",
    "Sidewalk Sorcerer",
    "Industrial Invoker",
    "Cybernetic Crusader",
    "Trashcan Tempest",
    "Dumpster Druid",
    "Bricklayer Battlemage",
    "Underground Oracle",
    "Streetlight Sage",
    "Alleycat Arcanist",
    "Steelworker Warden",
    "Traffic Tamer",
    "Riot Renegade",
    "Parkour Paladin",
    "Roof Runner",
    "Cityscape Champion",
    "Concrete Conjurer",
    "Urban Outlaw",
    "Subway Saboteur",
    "Freeway Fighter",
    "Steelworker Shaman",
    "Traffic Tamer",
    "Pavement Paladin",
    "Cityscape Sorcerer",
    "Underground Oracle",
    "Graffiti Guru",
    "Skyscraper Sentinel",
    "Rooftop Ranger",
    "Alleyway Adept",
    "Metro Mage",
    "Neon Navigator",
    "Concrete Guardian",
    "Street Samurai",
    "Sewer Squire",
    "Highway Hunter",
    "Subway Sentinel",
    "Gutter Guardian",
    "Urban Enforcer",
    "Cityscape Slicer",
    "Alleycat Arcanist",
    "Bricklayer Battlemage",
    "Dumpster Druid",
    "Trashcan Tempest",
    "Sidewalk Sorcerer",
    "Industrial Invoker",
    "Cybernetic Crusader",
    "Riot Renegade",
    "Streetlight Sage",
    "Parkour Paladin",
    "Roof Runner",
    "Graffiti Goliath",
    "Steelworker Warden",
    "Freeway Fury"
    "Half-Orc Rockstar",
    "Goblin Gadgeteer",
    "Dwarf Diviner",
    "Kobold Knight",
    "Centaur Chef",
    "Minotaur Mathematician",
    "Satyr Surgeon",
    "Gnoll Gardener",
    "Lizardfolk Linguist",
    "Aasimar Astronomer",
    "Tiefling Taxidermist",
    "Firbolg Fashionista",
    "Tabaxi Tactician",
    "Kenku Chef",
    "Aarakocra Accountant",
    "Genasi Geologist",
    "Triton Troubadour",
    "Goliath Glassblower",
    "Half-Elf Harpist",
    "Half-Orc Historian",
    "Gith Geneticist",
    "Yuan-ti Yodeler",
    "Hobgoblin Hypnotist",
    "Bugbear Barber",
    "Githzerai Glaciologist",
    "Duergar Dancer",
    "Tortle Tattoo Artist",
    "Changeling Chemist",
    "Shifter Sculptor",
    "Warforged Winemaker",
    "Goliath Grammarian",
    "Kalashtar Cartographer",
    "Loxodon Luthier",
    "Simic Hybrid Stuntman",
    "Vedalken Ventriloquist",
    "Viashino Violinist",
    "Verdan Vintner",
    "Locathah Librarian",
    "Siren Sculptor",
    "Leprechaun Lumberjack",
    "Myconid Mime",
    "Thri-kreen Tailor",
    "Shardmind Surgeon",
    "Warforged Wrestler",
    "Satyr Sushi Chef",
    "Lizardfolk Librarian",
    "Aasimar Acrobat",
    "Tabaxi Tattoo Artist",
    "Kenku Kite Maker",
    "Aarakocra Armorer",
    "Genasi Glassblower",
    "Triton Tinkerer",
    "Goliath Gardener",
    "Half-Elf Herbalist",
    "Half-Orc Harpist",
    "Gith Gemcutter",
    "Yuan-ti Yo-Yo Expert",
    "Hobgoblin Holographer",
    "Bugbear Beekeeper",
    "Githzerai Glassblower",
    "Duergar Diver",
    "Tortle Taxidermist",
    "Changeling Chess Master",
    "Shifter Singer",
    "Warforged Woodworker",
    "Goliath Gemologist",
    "Kalashtar Kite Maker",
    "Loxodon Leatherworker",
    "Simic Hybrid Sculptor",
    "Vedalken Violinist",
    "Viashino Vintner",
    "Verdan Ventriloquist",
    "Locathah Luthier",
    "Siren Shipwright",
    "Leprechaun Lute Player",
    "Myconid Mountaineer",
    "Thri-kreen Tailor",
    "Shardmind Sculptor",
    "Warforged Weaver",
    "Satyr Sleuth",
    "Lizardfolk Lexicographer",
    "Aasimar Archaeologist",
    "Tabaxi Topiary Artist",
    "Kenku Kineticist",
    "Aarakocra Alchemist",
    "Genasi Gemcutter",
    "Triton Tapestry Weaver",
    "Goliath Glassblower",
    "Half-Elf Horticulturist",
    "Half-Orc Harpsichordist",
    "Gith Gourmet",
    "Yuan-ti Yodeler",
    "Hobgoblin Haberdasher",
    "Bugbear Brewer",
    "Githzerai Glassblower",
    "Duergar Dancer",
    "Tortle Taxidermist",
    "Changeling Calligrapher",
    "Shifter Sculptor",
    "Warforged Wordsmith",
    "Shadowdancer",
    "Invoker",
    "Spellbinder",
    "Battlemage",
    "Soulbinder",
    "Sentinel",
    "Spellwright",
    "Warden",
    "Chronomancer",
    "Dragonslayer",
    "Ravager",
    "Beastmaster",
    "Pyromancer",
    "Illusionist",
    "Geomancer",
    "Necromancer",
    "Sorcerer",
    "Rogue",
    "Knight",
    "Druid",
    "Shaman",
    "Cleric",
    "Paladin",
    "Barbarian",
    "Bard",
    "Monk",
    "Ranger",
    "Warlock",
    "Wizard",
    "Fighter",
    "Assassin",
    "Thief",
    "Hunter",
    "Swashbuckler",
    "Warrior",
    "Sellsword",
    "Berserker",
    "Summoner",
    "Juggernaut",
    "Trickster",
    "Alchemist",
    "Brawler",
    "Archer",
    "Conjurer",
    "Illusionist",
    "Bladesinger",
    "Spellblade",
    "Bountyhunter",
    "Crusader",
    "Runemage",
    "Gunslinger",
    "Shadowblade",
    "Swordmaster",
    "Spellcaster",
    "Skald",
    "Warlord",
    "Executioner",
    "Inquisitor",
    "Riftwalker",
    "Swordmage",
    "Warpriest",
    "Venomancer",
    "Mystic",
    "Elementalist",
    "Artificer",
    "Celestial",
    "Voidwalker",
    "Soothsayer",
    "Bladeweaver",
    "Diviner",
    "Stormcaller",
    "Deathdealer",
    "Corsair",
    "Oracle",
    "Tactician",
    "Hellion",
    "Apocalypse",
    "Bloodmage",
    "Champion",
    "Crusader",
    "Dervish",
    "Exorcist",
    "Gladiator",
    "Heretic",
    "Hexer",
    "Nightblade",
    "Pirate",
    "Runesmith",
    "Sage",
    "Scholar",
    "Shadowcaster",
    "Slayer",
    "Spellslinger",
    "Templar",
    "Voidwalker",
    "Witch",
    "Zealot"
]